name: feedback_package_flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Feedback package
  feedback: ^2.6.0
  # To save feedback image in files
  path_provider: ^2.0.10
  # To send feedback as email
  flutter_email_sender: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true